### ISSUE TITLE
CloudFlare not forwarding via SRV records

### ISSUE THREAD

**Issue by SuspiciousEsports** [DefectiveMafia/DefectiveMafia#1]
Since switch to CF the domains mc.defectivemafia.com and v.mc.defectivemafia.com are not supporting their SRV records correctly, meaning the user needs to input the full address with port to access.

**Comment by bhygate** [comment]
CF are aware of the issues, waiting for support response.

Temporary addresses created at -
Vanilla: dmserver.gq:25566
Modded: dmserver.gq:25567
- as temp workaround

**Comment by SuspiciousEsports** [comment]
Issue may have resolved itself, suspecting it was simply a caching issue.

Will monitor for a while before marking fixed

**Comment by SuspiciousEsports** [comment]
Seems to be resolved for Minecraft but not TS, looking into alternative options (eg TSDNS)

**Comment by BrusherTheHusky** [comment]
Appears to be fixed for TS as well now, will close but keep monitoring.
